[package]
name = "xgate-tool"
version = "0.1.0"
authors = ["Vincent Chi <song374561@chivincent.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
